#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
script_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd -- "$script_root"
ENV_FILE="$script_root/.env.server"
umask 077
banner "Host Onshape Slicer Link"
say "This is the one-time application operator setup. Use the replacement test account."
say "Stages: Render hosting, Onshape registration, service credentials, desktop connection."
say "Render's proposed Starter service and 1 GB disk cost about US$7.25/month before extras."
confirm "Continue with these setup stages?" || exit 0

stage "Render hosting"
key=$(_existing OSL_ENCRYPTION_KEY || true)
if [[ -z "$key" ]]; then
  command -v openssl >/dev/null 2>&1 || { warn "OpenSSL is required here. Run this wizard in Git Bash."; exit 1; }
  key=$(openssl rand -base64 32 | tr '/+' '_-')
  write_env OSL_ENCRYPTION_KEY "$key"
fi
say "The encryption key is saved in .env.server. Keep a secure backup; do not share it in chat."
open_url "https://dashboard.render.com/"
step "Sign in and authorize Render to access only the private LeoHougaard/onshape-slicer-link repository."
step "Choose New > Blueprint, select that repository, and use its render.yaml."
say "Source repository: https://github.com/LeoHougaard/onshape-slicer-link"
step "For OSL_ENCRYPTION_KEY, paste the value from .env.server. Leave the OAuth fields empty for now."
step "Review Starter and the 1 GB disk. Create the paid service only if you accept the cost."
pause "Once the service is deployed, press Enter."
ask OSL_ORIGIN "Paste the service's HTTPS onrender.com address:"
[[ "$OSL_ORIGIN" =~ ^https://[A-Za-z0-9.-]+(:[0-9]+)?/?$ ]] || { warn "Expected an HTTPS origin without a path."; exit 1; }
OSL_ORIGIN="${OSL_ORIGIN%/}"
write_env OSL_ORIGIN "$OSL_ORIGIN"
open_url "$OSL_ORIGIN/health"
pause "Check that the page reports status ok and protocol 1, then press Enter."

stage "Private Onshape application"
open_url "https://cad.onshape.com/user/settings"
step "Use the designated replacement test account. Open My account > Developer > OAuth applications."
step "Create a new OAuth application named Slicer Link, type Integrated Cloud App."
step "Use a unique primary format, for example com.leo.onshape-slicer-link."
step "Enable only Read documents, OAuth2Read."
step "Redirect URL: $OSL_ORIGIN/auth/callback"
step "OAuth URL: $OSL_ORIGIN/"
step "Create the app. Copy the secret now; Onshape shows it only once."
ask ONSHAPE_CLIENT_ID "Paste the OAuth client ID from Keys and secret:"
ask_secret ONSHAPE_CLIENT_SECRET "Paste the client secret (hidden):"
[[ -n "$ONSHAPE_CLIENT_ID" && -n "$ONSHAPE_CLIENT_SECRET" ]] || { warn "Both credentials are required."; exit 1; }
write_env ONSHAPE_CLIENT_ID "$ONSHAPE_CLIENT_ID"
write_env ONSHAPE_CLIENT_SECRET "$ONSHAPE_CLIENT_SECRET"
step "On the app's Extensions tab, choose Add extension."
step "Name: Slicer Link. Location: Element right panel. Context: Part Studio."
say 'Copy this action URL, including the literal replacement fields:'
printf '  %s/?documentId={$documentId}&workspaceId={$workspaceOrVersionId}&workspaceType={$workspaceOrVersion}&elementId={$elementId}&configuration={$configuration}\n' "$OSL_ORIGIN"
note "Onshape appends server automatically. No action type is needed for the panel."
step "On Details, create a private store entry with the same application type."
step "Complete the required description, support contact, vendor, and version fields with your own information."
open_url "https://cad.onshape.com/appstore"
step "Find your private app, subscribe to it, and refresh the test document."
pause "Press Enter when the private app is subscribed."

stage "Connect the hosted service"
open_url "https://dashboard.render.com/"
step "Open the Slicer Link service > Environment."
step "Use Add from .env to import .env.server from this project. Keep the existing encryption key."
step "Save, rebuild, and deploy the service. Keep exactly one instance."
step "Keep .env.server out of Git and out of the desktop package. It contains server secrets."
pause "Press Enter when the deployment is live."
open_url "$OSL_ORIGIN/"
step "Choose Connect to Onshape and authorize the test account. Allow the sign-in popup."
pause "Press Enter after Slicer Link shows your connected account."

stage "Connect the desktop helper"
say "Install dist/OnshapeSlicerLink-Setup-x86_64.exe on Windows."
say "The first development build asks for the public application address:"
say "$OSL_ORIGIN"
step "Choose a project folder and Connect with Onshape, then Pair this computer in the browser."
step "In Onshape, open Slicer Link from a Part Studio, choose a solid part, and refresh it."
step "Choose Open helper, check the folder, then Save refreshed files."
step "Import the STL once into the official slicer and save the .3mf beside it."
step "Change CAD, refresh again, then use native Reload from disk in the slicer."
note "See docs/user-test.md for the short first-test checklist. Do not slice or print until you choose to."
pause "Press Enter when you are ready to start your first test."
finish
